Ví dụ: 3.3.2.3

In [ ]:
import numpy as np 
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
A[5:]

array([5, 6, 7, 8, 9])

In [ ]:
A[:5]

array([0, 1, 2, 3, 4])

In [ ]:
A[4:7]

array([4, 5, 6])

Ví dụ: 3.3.2.4- Mảng đa chiều 

In [ ]:
import numpy as np 
B = np.array([[1,2,3,4], [5,6,7,8], [9,0,1,2]])
B

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [ ]:
B[:2,:3] #2 dòng 3 cột 

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
B[:3,::2] # 2 DẤU 2 CHẤM TỨC LÀ : BẮT ĐẦU 3 ĐIỂM DỪNG 0 BƯỚC NHẢY LÀ 2

array([[1, 3],
       [5, 7],
       [9, 1]])

In [ ]:
B[::-1, ::-1] # Lệch mảng 

array([[2, 1, 0, 9],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

Ví dụ: 3.3.2.5

In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print("Cột đầu tiên của mảng arr là: ",arr[:,0])    
print("Hàng đầu tiên của mảng arr là:",arr[0,:]) 
print("Hàng đầu tiên của mảng arr là:",arr[0]) 

Cột đầu tiên của mảng arr là:  [1 4 7]
Hàng đầu tiên của mảng arr là: [1 2 3]
Hàng đầu tiên của mảng arr là: [1 2 3]


Ví dụ 3.3.3.1

In [ ]:
import numpy as np 
 
# Tạo mảng 2 chiều 3x3 
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]]) 
 
# Lấy view mới chỉ chứa 2 dòng và 2 cột của mảng gốc 
arr_view = arr_2d[:2, :2].view() 
print(arr_view)   #in mảng con arr_con vừa được slicing từ hàm view

[[1 2]
 [4 5]]


In [ ]:
arr_view[0, 0] = 100 #Chỉnh sửa phần tử ở dòng 0, cột 0 thành 10. 
print(arr_view) 

[[100   2]
 [  4   5]]


In [ ]:
print("Mảng gốc sau khi thay đổi giá trị trong view:") 
print(arr_2d) 

Mảng gốc sau khi thay đổi giá trị trong view:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


ví dụ 3.3.3.1.1

In [ ]:
arr_view[0, 1] = 12
print(arr_view)

[[100  12]
 [  4   5]]


Ví dụ 3.3.3.2

In [ ]:
 
sub_arr=arr[:2,:2] #slicing mảng con lấy 2 dòng, 2 cột của mảng arr 
print(sub_arr)

[[1 2]
 [4 5]]


In [ ]:
sub_arr[0,0]=10  #Chỉnh sửa phần tử ở dòng 0, cột 0 của mảng con thành 10. 
print(sub_arr) 

[[10  2]
 [ 4  5]]


In [ ]:
print(arr) 

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


3.3.3.3

In [ ]:
sub_arr_copy=arr[:2,:2].copy()  #Thêm phương thức copy(). 
print(sub_arr_copy)     #in mảng con vừa được copy. 

[[10  2]
 [ 4  5]]


In [ ]:
sub_arr_copy[0,0]=10    #sửa phần tử ở dòng 0, cột 0 của mảng                
                                                          # copy thành 10. 
print(sub_arr_copy) 

[[10  2]
 [ 4  5]]


In [ ]:
print(arr)     

Ví dụ 3.3.3.4

In [ ]:
arr=np.arange(1,10)            #Tạo mảng một chiều arr có 9 phần tử từ 1-9 
grid= arr.reshape((3,3))#chuyển đổi mảng arr thành mảng grid, 3x3 
grid #reshape : ko thay đổi mảng gốc , nó chỉ thay đổi hình dạng của bang

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Ví dụ: 3.3.3.5

In [ ]:
x = np.array([1, 2, 3]) 
x.reshape((1, 3))

array([[1, 2, 3]])

In [ ]:
x[np.newaxis, :] 

array([[1, 2, 3]])

In [ ]:
x.reshape((3, 1)) 

array([[1],
       [2],
       [3]])

In [ ]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

ví dụ 3.3.4.1

In [ ]:
x = np.array([1, 2, 3]) 
y = np.array([4, 5, 6]) 
np.concatenate([x,y]) 

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np 
a = np.array([[1, 2], 
              [3, 4]]) 
b = np.array([[5, 6], 
              [7, 8]]) 
# Kết hợp theo chiều đầu tiên (trục dọc/ trục 0) của mảng 
c = np.concatenate((a, b))  
print(c) 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
d = np.concatenate([a, b], axis=1) 
print(d) 

[[1 2 5 6]
 [3 4 7 8]]


Ví du: 3.3.4.2

In [ ]:
import numpy as np 
a = np.array([[1, 2], 
              [3, 4]]) 
b = np.array([[5, 6], 
              [7, 8]]) 
# Kết hợp theo chiều đầu tiên (trục dọc/ trục 0) của mảng 
c = np.vstack((a, b))  
 
# Kết hợp theo chiều ngang (trục ngang/ trục 1) của mảng 
d = np.hstack((a,b)) 
print(c) 
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


ví dụ 3.3.4.3

In [ ]:
import numpy as np 
arr = np.arange(10)   #Tạo mảng arr gồm 10 phần tử từ 0-9 
sub_arr1=np.split(arr,[3, 6]) #chia mảng arr theo chỉ mục [3, 6]  
#Phần đầu tiên bắt đầu từ chỉ mục 0 và kết thúc trước chỉ mục 3. 
#Phần thứ hai bắt đầu từ chỉ mục 3 và kết thúc trước chỉ mục 6. 
 
sub_arr2=np.split(arr,2) #chia mảng arr thành 2 phần bằng nhau  
print("Mảng con sub_arr1 là:", sub_arr1, "\n") 
print("Mảng con sub_arr2 là:", sub_arr2) 

Mảng con sub_arr1 là: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])] 

Mảng con sub_arr2 là: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


Ví dụ: 3.3.4.4

In [ ]:
import numpy as np 
arr = np.arange(16).reshape((4,4)) 
arr 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper,lower = np.vsplit(arr,2) #Tách theo trục ngang 
print("Kết quả sau khi tách từ mảng ban đầu \n") 
print(upper,"\n") 
print(lower,"\n") 

Kết quả sau khi tách từ mảng ban đầu 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 



3.3.5.1

In [ ]:
import numpy as np 
 
arr=np.array([1,2,3]) 
new_arr=np.append(arr,4) 
 
print(arr) 
print(new_arr)

[1 2 3]
[1 2 3 4]


In [ ]:
left,right=np.hsplit(arr,2)   #Tách theo trục dọc 
print("Kết quả sau khi tách từ mảng ban đầu \n") 
print(left,"\n") 
print(right,"\n") 


Kết quả sau khi tách từ mảng ban đầu 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 



Ví dụ 3.3.5.2

In [ ]:
#Thêm phần tử vào vị trí cụ thể trong mảng 1 chiều: 
 
arr = np.array([1, 2, 3, 4, 5]) 
new_element = 10 
index_to_insert = 2 
 
new_arr = np.insert(arr, index_to_insert, new_element) 
 
print(new_arr)   

[ 1  2 10  3  4  5]


In [ ]:
#Thêm phần tử vào vị trí cụ thể trong mảng 2 chiều: 
arr_2d = np.array([[1, 2], [3, 4], [5, 6]]) 
new_element = [7, 8] 
row_to_insert = 1 
 
new_arr_2d=np.insert(arr_2d,row_to_insert,new_element,axis=0) 
print(new_arr_2d) 

[[1 2]
 [7 8]
 [3 4]
 [5 6]]


Ví dụ 3.3.6.1

In [ ]:
#Tìm chỉ mục (vị trí) phần tử trong mảng 1 chiều: 
 
arr = np.array([1, 2, 3, 4, 5]) 
indices = np.where(arr==3) 
indices 

(array([2]),)

Ví dụ: 3.3.6.2

In [ ]:
arr = np.array([1, 2, 3, 4, 5]) 
indices = np.argwhere(arr==3) 
indices 

array([[2]])

Ví dụ: 3.3.6.3

In [ ]:
arr = np.array([1, 5, 2, 3, 4]) 
max_idx = np.argmax(arr) 
min_idx = np.argmin(arr) 
 
print(max_idx) 
print(min_idx) 

1
0


Ví dụ: 3.3.6.4

In [ ]:
arr = np.array([3, 1, 4, 2, 5]) 
sorted_arr_descending= np.sort(arr)[::-1] 
 
sorted_arr_descending

array([5, 4, 3, 2, 1])

In [ ]:
arr = np.array([3, 1, 4, 2, 5]) 
arr.sort()                   
 
arr[::-1]

array([5, 4, 3, 2, 1])

Ví dụ 3.3.7.1

In [ ]:
arr = np.array([3, 1, 4, 2, 5]) 
idx_to_delete = 2                 #Xóa phần tử 4 ở chỉ mục 2. 
new_arr=np.delete(arr,idx_to_delete) 
 
new_arr

array([3, 1, 2, 5])

In [ ]:
arr = np.array([3, 1, 4, 2, 5]) 
idx_to_delete = [1, 3] 
new_arr = np.delete(arr, idx_to_delete) 
 
new_arr

array([3, 4, 5])

In [ ]:
#Xóa phần tử trên mảng 2 chiều 
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
row_idx_to_delete = 1 
 
new_arr_2d = np.delete(arr_2d, row_idx_to_delete, axis=0) 

    Ví dụ: 3.3.7.2

In [ ]:
arr = np.array([1, 2, 3, 4, 5]) 
del arr 
arr

NameError: name 'arr' is not defined

Ví dụ: 3.3.7.3

In [ ]:
arr = np.array([1, 2, 3, 4, 5]) 
arr = None  
print(arr) 

None


Ví dụ: 3.3.8.2

In [ ]:
import numpy as np 
 
# Định nghĩa kiểu dữ liệu cho một Structured Array 
dtype = [('name', 'U20'), ('age', int), ('height', float)] 
 
# Tạo một Structured Array 
data = np.array([('Minh', 22, 165.5), 
                 ('Lan', 40, 160.0), 
                 ('Linh', 31, 165.0), 
                 ('Lương',18,166.5), 
                 ('Thanh',50, 170.0)], dtype=dtype) 
# Truy cập các trường bằng tên 
print(data['name'])    # In ra mảng 'name' 
print(data['age'])     # In ra mảng 'age' 
print(data['height'])  # In ra mảng 'height' 

['Minh' 'Lan' 'Linh' 'Lương' 'Thanh']
[22 40 31 18 50]
[165.5 160.  165.  166.5 170. ]


ví dụ: 3.4.1

In [ ]:
import numpy as np 
import time 
# Tạo một mảng NumPy với 100.000.000 phần tử 
arr = np.arange(100000000, dtype=np.int64) 
# Tính tổng các phần tử của mảng bằng vòng lặp 
start_time = time.time() 
total = np.int64(0) 
for num in arr: 
    total += num 
end_time = time.time() 
elapsed_time_loop = end_time - start_time 
print("Tổng các phần tử mảng arr khi sử dụng vòng lặp:", total) 
print("Thời gian (giây) khi sử dụng vòng lặp:", elapsed_time_loop) 
# Tính tổng các phần tử của mảng bằng np.sum() 
start_time = time.time() 
total = np.sum(arr) 
end_time = time.time() 
elapsed_time_npsum = end_time - start_time 
print("Tổng các phần tử mảng arr khi sử dụng hàm np.sum():", total) 
print("Thời gian (giây) khi sử dụng np.sum():", elapsed_time_npsum) 
num_times_faster = elapsed_time_loop / elapsed_time_npsum 
print("Sử dụng vòng lặp chậm hơn: ~",int(num_times_faster),"lần") 

Tổng các phần tử mảng arr khi sử dụng vòng lặp: 4999999950000000
Thời gian (giây) khi sử dụng vòng lặp: 13.739453554153442
Tổng các phần tử mảng arr khi sử dụng hàm np.sum(): 4999999950000000
Thời gian (giây) khi sử dụng np.sum(): 0.0660247802734375
Sử dụng vòng lặp chậm hơn: ~ 208 lần


ví dụ: 3.4.2

In [ ]:
import numpy as np 
import timeit # Import thư viện timeit để đo thời gian thực thi của các đoạn code. 
 
# Tính tổng của mảng sử dụng Numpy 
np_setup = "import numpy as np; np_array = np.arange(1, 1000001)" 
np_code  = "np_sum = np.sum(np_array)" 
np_time  = timeit.timeit(stmt=np_code, setup=np_setup, number=10) 
 
# Tính tổng của danh sách sử dụng List 
list_setup = "list_array = list(range(1, 1000001))" 
list_code = "list_sum = sum(list_array)" 
list_time = timeit.timeit(stmt=list_code, setup=list_setup, 
number=10) 
 
print("Thời gian tính toán của Numpy:", np_time) 
print("Thời gian tính toán của List:", list_time) 
 
print("Numpy tính nhanh hơn List ở lượt chạy là ~ ", int(list_time/np_time), "lần!!")

Thời gian tính toán của Numpy: 0.012280100025236607
Thời gian tính toán của List: 0.07783720002043992
Numpy tính nhanh hơn List ở lượt chạy là ~  6 lần!!


Ví dụ 3.4.3.1

In [ ]:
import numpy as np 
 
arr1 = np.array([1, 2, 3]) 
arr2 = np.array([4, 5, 6]) 
 
#Phép Cộng:Sử dụng hàm np.add() hoặc toán tử '+'. 
Tong = np.add(arr1,arr2) 
#hoặc tong = arr1+arr2 
 
#Phép Trừ: Sử dụng hàm np.subtract() hoặc toán tử '-'. 
Hieu = np.subtract(arr1,arr2) 
#hoặc Tru = arr1-arr2 
 
#Phép Nhân: Sử dụng hàm np.multiply() hoặc toán tử '*' 
Tich = np.multiply(arr1,arr2) 
#Hoặc arr1*arr2 
 
#Phép Chia: Sử dụng hàm np.divide() hoặc toán tử '/' 
Thuong = np.divide(arr1,arr2) 
# Về sin cos tan, mp.sin(), np.cos(), np.tan, np.log(), np.log()^2,np.sprt()
 
print("Tổng của arr1 + arr2 là:",Tong) 
print("Hiệu của arr1 - arr2 là:",Hieu) 
print("Tích của arr1 * arr2 là:",Tich) 
print("Thương của arr1/arr2 là:",Thuong)

Tổng của arr1 + arr2 là: [5 7 9]
Hiệu của arr1 - arr2 là: [-3 -3 -3]
Tích của arr1 * arr2 là: [ 4 10 18]
Thương của arr1/arr2 là: [0.25 0.4  0.5 ]


Ví dụ: 3.4.3.1.1:

1. add – Cộng phần tử tương ứng

In [1]:
import numpy as np
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.add(a1, a2)   # ➜ array([5, 7, 9])


array([5, 7, 9])

2. subtract – Trừ phần tử tương ứng

In [2]:
np.subtract(a1, a2)   # ➜ array([-3, -3, -3])


array([-3, -3, -3])

3. multiply – Nhân phần tử tương ứng

In [3]:
np.multiply(a1, a2)   # ➜ array([4, 10, 18])


array([ 4, 10, 18])

4. divide – Chia phần tử tương ứng

In [ ]:
np.divide(a2, a1)  


array([4. , 2.5, 2. ])

5. floor_divide – Chia lấy phần nguyên

In [ ]:
np.floor_divide(a2, a1) 

array([4, 2, 2])

6. power – Lũy thừa

In [6]:
np.power(a1, a2) 

array([  1,  32, 729])

7. maximum – Lấy giá trị lớn nhất theo từng phần tử

In [7]:
np.maximum(a1, a2)  


array([4, 5, 6])

8. fmax – Giống maximum nhưng bỏ qua NaN

In [ ]:
a3 = np.array([1, 2, np.nan])
a4 = np.array([3, np.nan, 4])
np.fmax(a3, a4)  


array([3., 2., 4.])

9. minimum – Lấy giá trị nhỏ nhất theo từng phần tử

In [9]:
np.minimum(a1, a2)   


array([1, 2, 3])

10. fmin – Giống minimum nhưng bỏ qua NaN

In [10]:
np.fmin(a3, a4)   # ➜ array([1., 2., 4.])


array([1., 2., 4.])

11. mod – Lấy phần dư

In [ ]:
a2 = np.array([3, 4, 5])
np.mod(a2, 3)   


array([0, 1, 2])

12. copysign – Sao chép dấu

In [ ]:
x1 = np.array([1, -2, 3])
x2 = np.array([-4, 5, -6])
np.copysign(x1, x2)   


array([-1.,  2., -3.])

13. greater – lớn hơn (>)

In [ ]:
np.greater(a1, a2)   


array([False, False, False])

14. greater_equal – lớn hơn hoặc bằng (>=)

In [ ]:
np.greater_equal(a2, a1)  


array([ True,  True,  True])

In [15]:
# 15. less – nhỏ hơn (<)
np.less(a1, a2)   # ➜ array([ True, True, True])

# 16. less_equal – nhỏ hơn hoặc bằng (<=)
np.less_equal(a2, a1)   # ➜ array([False, False, False])

# 17. equal – bằng nhau (==)
np.equal(a1, a2)   # ➜ array([False, False, False])

# 18. not_equal – khác nhau (!=)
np.not_equal(a1, a2)   # ➜ array([ True, True, True])

# Các phép logic (với mảng Boolean)
a = np.array([True, True, False])
b = np.array([True, False, False])

# 19. logical_and – Phép “và” logic
np.logical_and(a, b)   # ➜ array([ True, False, False])

# 20. logical_or – Phép “hoặc” logic
np.logical_or(a, b)    # ➜ array([ True, True, False])

# 21. logical_xor – Phép “hoặc loại trừ” logic
np.logical_xor(a, b)   # ➜ array([False, True, False])

array([False,  True, False])

Ví dụ 3.4.3.3:

In [ ]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5]) 
 
# Căn bậc hai của các phần tử trong mảng 
kq_can_hai = np.sqrt(arr)  
 
# Lũy thừa 2 của các phần tử trong mảng 
kq_luy_thua_2 = np.power(arr, 2) 
 
# Logarit tự nhiên (cơ số e) của các phần tử trong mảng 
kq_Logarit = np.log(arr) 
  
# Giá trị tuyệt đối của các phần tử trong mảng 
kq_tri_tuyet_doi = np.abs(arr) 
 
# Hàm logic NOT (đảo ngược giá trị) của các phần tử trong mảng 
kq_not_logic = np.logical_not(arr) 
#Hàm sin của các phần tử trong mảng 
kq_sin=np.sin(arr) 
print("Căn bậc hai của từng phần tử trong mảng là: ", kq_can_hai)  
print("Lũy thừa bậc hai của từng phần tử trong mảng là: ", kq_luy_thua_2) 
print("Logarit của từng phần tử trong mảng là: ", kq_Logarit)  
print("Trị tuyệt đối của từng phần tử trong mảng là: ", kq_tri_tuyet_doi)  
print("Kết quả đảo ngược giá trị của các phần tử trong mảng là:", kq_not_logic) 
print("Kết quả hàm sin của các phần tử trong mảng là:", kq_sin)

Căn bậc hai của từng phần tử trong mảng là:  [1.         1.41421356 1.73205081 2.         2.23606798]
Lũy thừa bậc hai của từng phần tử trong mảng là:  [ 1  4  9 16 25]
Logarit của từng phần tử trong mảng là:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Trị tuyệt đối của từng phần tử trong mảng là:  [1 2 3 4 5]
Kết quả đảo ngược giá trị của các phần tử trong mảng là: [False False False False False]
Kết quả hàm sin của các phần tử trong mảng là: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


Ví dụ: 3.4.4.1

In [ ]:
import numpy as np 
arr1 = np.array([0,1,2]) 
arr2 = np.array([5,5,5]) 
arr1 + arr2 

array([5, 6, 7])

Ví dụ: 3.4.4.2

In [ ]:
import numpy as np 
arr1 = np.array([0,1,2])
arr1 + 5

array([5, 6, 7])

Ví dụ: 3.4.4.3

In [ ]:
import numpy as np 
arr = np.array([0,1,2]) 
arr 

array([0, 1, 2])

In [ ]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr + M

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

Ví dụ 3.4.4.4

In [ ]:
import numpy as np 
arr1 = np.arange(3)
arr2 = np.arange(3)[:,np.newaxis]
print(arr1)
print(arr2)

[0 1 2]
[[0]
 [1]
 [2]]


In [ ]:
arr1 + arr2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Ví dụ 3.4.3.3

In [ ]:
import numpy as np 
# Tạo mảng dữ liệu với kích thước lớn (1000 phần tử) 
data = np.random.randint(100, 200, size=1000) 
# Tạo một giá trị trung bình (số thực) 
mean_value = np.array([data.mean()]) 
# Tính tỷ lệ phần trăm tăng trưởng bằng cách áp dụng broadcasting 
percentage_growth= (data - mean_value) / mean_value * 100 
# In ra 10 phần tử đầu tiên của mảng dữ liệu và tỷ lệ phần trăm tăng trưởng 
print("Dữ liệu gốc:", data[:10]) 
print("Tỷ lệ phần trăm tăng trưởng:", 
percentage_growth[:10])

Dữ liệu gốc: [190 177 187 190 149 107 112 140 194 197]
Tỷ lệ phần trăm tăng trưởng: [ 26.3449083   17.70025668  24.3499887   26.3449083   -0.91899296
 -28.84786743 -25.52300142  -6.90375178  29.00480111  30.99972071]
